### ISSUE TITLE
ES2 external battery help?

### ISSUE THREAD

**Issue by Skilledcamman** [lekrsu/shfw-walkthrough#7]
I want to add an external battery to the es2. Someone on discord has stated that this can be done by connecting the battery directly to the xt30 connecter which is initially used for the official ninebot external battery.
Can someone help me with this.
Im gonna be using a battery similar to this 
https://www.facebook.com/marketplace/item/243568398841038/?ref=search&referral_code=null&referral_story_type=post&tracking=browse_serp%3A89faa69b-15fa-4951-9fe4-c79b5f87ee0b

**Comment by lekrsu** [comment]
Your question isn't related to this repo. This isn't a help group. I saw your conversation on Discord a couple hours ago. Continue there.

Consider this issue report closed.
