### ISSUE TITLE
Error while charging ninebot es4 from 4a charger on shfw 133-3.7.2

### ISSUE THREAD

**Issue by AndreyKrasnov06** [lekrsu/shfw-walkthrough#8]
When I updated from 133-3.7.1 to 133-3.7.2 my scooter stopped charging on the 4a charger, a red wrench appears briefly and charging restarts.This is not observed on firmware 255-3.7.2, but it does not display the external battery in scootbatt on 255 firmware. Please fix this:(

**Comment by lekrsu** [comment]
> When I updated from 133-3.7.1 to 133-3.7.2 my scooter stopped charging on the 4a charger, a red wrench appears briefly and charging restarts.This is not observed on firmware 255-3.7.2, but it does not display the external battery in scootbatt on 255 firmware. Please fix this:(

Bug reports go there, thanks.
https://github.com/scooterhacking/scooterhacking-issues-public/issues/
